name: untitled10
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-34.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  fluttertoast: ^8.2.2
  image_picker: ^0.8.5
  jiffy: ^6.2.1

  #state management
  flutter_bloc: ^8.1.3

#  local storage
  shared_preferences: ^2.2.2

  #firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/
